---
- name: Create firewall rules directory
  file:
    path: /etc/firewall
    state: directory

- name: Set iptables rules
  copy:
    src: firewall-enable.sh
    dest: /etc/firewall/firewall-enable.sh
    mode: a+x

- name: Set the firewall service
  copy:
    src: firewall.service
    dest: /etc/systemd/system/firewall.service

- name: Enable firewall
  systemd:
    name: firewall
    state: started
    enabled: yes

- name: Set the new IP static
  template:
    src: static.network
    dest: /etc/systemd/network/static.network

- name: Disable network service
  service:
    name: systemd-networkd
    state: stopped
    enabled: no

- name: Enable systemd-networkd service
  service:
    name: systemd-networkd
    state: started
    enabled: yes
